- name: install node exporter
  become: yes
  hosts: all
  roles:
  - node_exporter

- name: install elasticsearch
  become: yes
  hosts: servera
  roles:
  - elasticsearch
  - logstash

- name: install kibana
  become: yes
  hosts: serverb
  roles:
  - kibana

- name: install prometheus/grafana
  become: yes
  hosts: localhost
  roles:
  - prometheus
  - grafana